return {
    [0]={
        equipName="Rusty Katana",
        equipDesc="A rusty old katana.",
        equipTier="0",
        equipSlotType="24",
        equipBagType="0"},
    [1]={
        equipName="Magic Pearl",
        equipDesc="A simple pearl that eminates a magic essence",
        equipTier="0",
        equipSlotType="30",
        equipBagType="0"},
    [2]={
        equipName="Makeshift Turret",
        equipDesc="A simple blueprint for making a turret out of spair materials",
        equipTier="0",
        equipSlotType="32",
        equipBagType="0"},
    [3]={
        equipName="Basic Star",
        equipDesc="A basic ninja-star.",
        equipTier="0",
        equipSlotType="25",
        equipBagType="0"},
    [4]={
        equipName="Worn Halo",
        equipDesc="An old halo that could be mistaken for scrap metal.",
        equipTier="0",
        equipSlotType="26",
        equipBagType="0"},
    [5]={
        equipName="Lizard Cut",
        equipDesc="A simple technique used by samurai-trainees",
        equipTier="0",
        equipSlotType="27",
        equipBagType="0"},
    [6]={
        equipName="Bunny Scroll",
        equipDesc="A very simple scroll that summons a cute bunny",
        equipTier="0",
        equipSlotType="28",
        equipBagType="0"},
    [7]={
        equipName="Flint Spear",
        equipDesc="This wooden spear's inexpensive flint head makes it perfect for training",
        equipTier="0",
        equipSlotType="29",
        equipBagType="0"},
    [8]={
        equipName="Snake Totem",
        equipDesc="A simple totem that turns enemies into snakes",
        equipTier="0",
        equipSlotType="31",
        equipBagType="0"}
    }